version: "3.8"
services:
  backend:
    image: dankovtsev.pro:5000/service-content
    command: ["0.0.0.0", "50101"]
    ports:
      - "50101:50101"
    networks:
      - backend
  database:
    image: dankovtsev.pro:5000/utils/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    driver: bridge
